### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by daniel-anton** [zegl/kube-score#639]
**Which version of kube-score are you using?**

> kube-score version: 1.19.0

For previous versions 1.17 and 1.18 everything is ok.

**What did you do?**

# kube-score list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb82a43]

goroutine 1 [running]:
github.com/zegl/kube-score/score.RegisterAllChecks({0xe2e6f0, 0xc000206120}, 0x0?, 0x0)
        /Users/gustav/src/kube-score/score/score.go:34 +0x283
main.listChecks({0x7ffd15c5b70b, 0xa}, {0xc000034040, 0x0, 0x0})
        /Users/gustav/src/kube-score/cmd/kube-score/main.go:298 +0x1d8
main.main.func2({0x7ffd15c5b70b?, 0xc00013ff10?}, {0xc000034040?, 0x4?, 0xc0000b88a0?})
        /Users/gustav/src/kube-score/cmd/kube-score/main.go:44 +0x1d
main.main()
        /Users/gustav/src/kube-score/cmd/kube-score/main.go:68 +0x391

**What did you expect to see?**

# kube-score list | awk -F, '{ print  $1 }'
deployment-strategy
deployment-replicas
ingress-targets-service

**What did you see instead?**

kube-score list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb82a43]

goroutine 1 [running]:
github.com/zegl/kube-score/score.RegisterAllChecks({0xe2e6f0, 0xc000206120}, 0x0?, 0x0)
        /Users/gustav/src/kube-score/score/score.go:34 +0x283
main.listChecks({0x7ffd15c5b70b, 0xa}, {0xc000034040, 0x0, 0x0})
        /Users/gustav/src/kube-score/cmd/kube-score/main.go:298 +0x1d8
main.main.func2({0x7ffd15c5b70b?, 0xc00013ff10?}, {0xc000034040?, 0x4?, 0xc0000b88a0?})
        /Users/gustav/src/kube-score/cmd/kube-score/main.go:44 +0x1d
main.main()
        /Users/gustav/src/kube-score/cmd/kube-score/main.go:68 +0x391

**Comment by zegl** [comment]
Hey! Sorry about that, this bug has been fixed on the latest master. I'll make a new release of cube-score soon that includes the fix.

**Comment by Loic-Nicolle** [comment]
Hi, I'm still affected by this bug. Do you know when the next release will be ?
